FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# raploco

A Simple tasker

## Check API Health [/ok]

### Get status [GET]
+ Response 200 (application/json)

        {
            "message":"ok"
        }
        


## Users Collection [/questions]

### Create User [POST]

    {
        "name" : "user_name"
    }


+ Response 201 (application/json)

        {
            "id" : 1,
            "name" : "user_name",
            "token" : "awsedrftgyhujikoklp"
        }