FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# raploco

A Simple tasker

## Check API Health [/ok]

### Get status [GET]
+ Response 200 (application/json)

        {
            "message":"ok"
        }
        


## Users Collection [/users]

### Create User [POST]

+ Response 201 (application/json)

        {
            "id" : 1,
            "name" : "user_name",
            "token" : "awsedrftgyhujikoklp",
            "created_at": "2017-09-10T01:59:30.915Z",
            "updated_at": "2017-09-10T01:59:30.915Z"
        }

### Get a User [GET /users/{id}]

+ Response 200

        {
            "id": 2,
            "name": "user_name",
            "created_at": "2017-09-10T01:59:30.915Z",
            "updated_at": "2017-09-10T01:59:30.915Z"
        }

## Tasks Collection [/tasks]
### Create tasks[POST]
+ Request

        {
            "name":"task_name",
            "cost": 20,
            "deadline": "2017-09-10T01:59:30.915Z",
            "created_at": "2017-09-10T01:59:30.915Z",
            "updated_at": "2017-09-10T01:59:30.915Z"
        }
    
    + Headers

            X-Token: awsedrftgyhujikoklp


            
+ Response 201

        {
            "id": 1,
            "name":"task_name",
            "cost": 20,
            "deadline": "2017-09-10T01:59:30.915Z"
            "created_at": "2017-09-10T01:59:30.915Z",
            "updated_at": "2017-09-10T01:59:30.915Z"
        }


### Get All tasks[GET]
+ Request

    + Headers

            X-Token: awsedrftgyhujikoklp


+ Response 200

        {"tasks":[
            {
                "id": 1,
                "name": "task_name",
                "cost": 20,
                "deadline":"2017-09-10T01:59:30.915Z",
                "created_at": "2017-09-10T01:59:30.915Z",
                "updated_at": "2017-09-10T01:59:30.915Z"
            },            {
                "id": 2,
                "name": "next_task_name",
                "cost": 40,
                "deadline":"2017-09-10T01:59:30.915Z",
                "created_at": "2017-09-10T01:59:30.915Z",
                "updated_at": "2017-09-10T01:59:30.915Z"A
            },
            
        ]}