FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# raploco

A Simple tasker

## Check API Health [/ok]

### Get status [GET]
+ Response 200 (application/json)

        {
            "message":"ok"
        }
        


## Users Collection [/users]

### Create User [POST]

+ Response 201 (application/json)

        {
            "id" : 1,
            "name" : "user_name",
            "token" : "awsedrftgyhujikoklp"
        }

### Get a User [GET /users/{id}]

+ Response 200

        {
            "id": 2,
            "name": "user_name"
        }

## Tasks Collection [/tasks]

### Get All tasks[GET]
+ Request

    + Headers

            X-Token: awsedrftgyhujikoklp


+ Response 200

        {"tasks":[
            {
                "id": 1,
                "name": "task_name",
                "deadline":"2017-09-10 20:34:16 +0900",
                "cost": 20,
                "created_at": "2017-09-09 20:34:16 +0900",
            },            {
                "id": 2,
                "name": "next_task_name",
                "deadline":"2017-09-09 20:34:16 +0900",
                "cost": 40,
                "created_at": "2017-09-08 20:34:16 +0900",
            },
            
        ]}